### PR TITLE
Add Sentry support to unilog

### PR DESCRIPTION
**Pull request by julia-stripe**
r? @rb-stripe

This adds Sentry support to unilog. I tested it from the command line -- you can see an example of an exception it created at https://sentry.qa.corp.stripe.com/stripe/sys-cron-jobs/issues/29132/

I don't know exactly how this will affect backwards compatibility for the unilog library -- it adds a new optional field to a struct, which I feel like should be fine?

### CODE REVIEW

**Comment by rb-stripe** [comment]
cool :) I couldn't figure out how mailto or sentrydsn got passed in (and spot checking the kinsky box shows no command line options to unilog apart from `-a`. It can be a different PR but this whole thing was prompted by unilogs trying to email so we'd need to default mailto to be empty and the dsn to be whatever (the sys one seems fine, or we can make another just for unilog).

**Comment by julia-stripe** [comment]
Right! I should have mentioned that.

The `MailTo` and `MailFrom` options get set here: https://github.com/stripe-internal/unilog.stripe/blob/master/main.go#L65-L66. We'll need to do something different from that to set the Sentry DSN though.

**Comment by rb-stripe** [comment]
The code does seem to call parseFlag at some point, when you tested it did you pass the DSN in with a `--sentrydsn`? I'm hoping you say yes since we can then update the puppet unilog thing to just include that, and then distribute that using the appropriate scheme (I think we consider them slightly secret but I'm not sure if that was an accident).

**Comment by rb-stripe** [comment]
oh, also
👍 
since the code changes here are good

**Comment by julia-stripe** [comment]
yeah I tested with the `--sentrydsn` flag and it worked

**Comment by ChimeraCoder** [comment]
Retroactive lgtm (Observability now maintains Unilog, though we didn't really broadcast that officially, so you wouldn't have known. :) )


@rb-stripe As it happens, Sentry DSNs aren't really secret. They "look" like secrets, and we happen to manage them using puppet secrets, but having them exposed isn't actually a problem. (We have an amusing comment somewhere that documents this, which I can find if you'd like a chuckle.)

**Pull request merged**
